# fly.toml app configuration file generated for bwc-verify-bot on 2023-07-31T23:40:10+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bwc-verify-bot"
primary_region = "ams"

