# fly.toml app configuration file generated for bwc-verify-bot on 2023-07-31T23:40:10+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bwc-verify-bot"
primary_region = "ams"

[[services]]
  internal_port = 5000
  protocol = "tcp"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
